### ISSUE TITLE
Example are broken

### ISSUE THREAD

**Issue by rizkyramadhan** [nowaalex/af-virtual-scroll#2]
https://nowaalex.github.io/af-virtual-scroll/website/#/examples/table/simple

shows wrong example

**Comment by nowaalex** [comment]
I am rewriting examples, soon everything will be ok!

**Comment by rizkyramadhan** [comment]
https://nowaalex.github.io/af-virtual-scroll/website/#/examples/table/simple

Now, it shows 404. I hope you are doing well

**Comment by nowaalex** [comment]
https://nowaalex.github.io/af-virtual-scroll/website/
Thank you for keeping interest to my library!
It is mainly used in my internal projects, so changes may happen fast until I get everything stable.
Basic examples are alive, docs will be soon.

**Comment by nowaalex** [comment]
Repaired examples and renewed playground
