### ISSUE TITLE
Chrome freezing problem when scrolling

### ISSUE THREAD

**Issue by syllith** [nowaalex/af-virtual-scroll#26]
Hey bud, hope all is well. The list has been working great since you addressed those issues a while back. I'm having a little problem now that my team recently brought to my attention and it seems to be with the package itself, as it's happening on your sample site as well. 

The problem is, on Chrome only, when scrolling WITHOUT moving your mouse, scrolling completely stops until the mouse is moved again. I've attached a video that attempts to demonstrate this, but you might need to try it yourself to fully understand the problem. 

I don't ever recall this being an issue, and my suspicion is that the new Chrome version 100 that came out might be the source of the problem. I feel I would have remember that being an issue in the past and would have brought it to your attention sooner. If you could please look into this, that would be fantastic. Thank you
![screen-capture](https://user-images.githubusercontent.com/42996651/174459260-36b91023-bbef-433d-9470-1dff2be5a84b.gif)
!

**Comment by nowaalex** [comment]
@syllith seems like chrome issue... needs some investigation

**Comment by nowaalex** [comment]
Interesting issue...seems like I found the reason.
[New FAQs page](https://af-virtual-scroll.vercel.app/faq)

If you just use List or Table components - you just need to upgrade the library. All new styles are added automatically. I have also removed style.css file in new versions (check documentation to see all changes)

**Comment by syllith** [comment]
Great, thank you for the swift response. I'm redoing my project in typescript on React 18. I'm getting errors installing due to peer dependencies. Am I safe to install with --legacy
![Untitled](https://user-images.githubusercontent.com/42996651/174500096-b4788659-dad7-4b35-a382-6ac950942a5a.png)
-peer-deps? Are you considering updating your package to be fully compatible with React 18?

**Comment by nowaalex** [comment]
Added react 18 support. Please upgrade

**Comment by syllith** [comment]
You are incredibly quick, thank you so much. I'm currently reconstructing the list portion of my project, I will let you know if there are any problems. Thank you again!

**Comment by syllith** [comment]
Everything is working perfectly. Thank you again, you're amazing. Closing the issue now since you've addressed it perfectly. Keep up the good work. This truly is an amazing package you've made!

**Comment by syllith** [comment]
Oh hey, side note, did you happen to fix a problem when scrolling manually with the mouse on the scroll bar? The scroll bar position used to get unaligned with the mouse when scrolling very quickly, but it looks to be resolved?

**Comment by nowaalex** [comment]
Yes, I have this issue on React 18, will investigate this problem. Could you please start new issues in future?)

**Comment by syllith** [comment]
Of course. I'm sorry. For some reason it seemed to be working yesterday, but now that I've rechecked, the problem still seems to be there. I will start a new issue about it now, just so it's official
