### ISSUE TITLE
NPM Error: Please verify that the package.json has a valid "main" entry

### ISSUE THREAD

**Issue by aaron5670** [nowaalex/af-virtual-scroll#8]
Hi @nowaalex 

I got the following error when I try your library.. :(
I'm trying to get your package working with Next.js... Can you help me?

![image](https://user-images.githubusercontent.com/17295145/113332259-39ed7800-9321-11eb-8745-e102747a51d2.png)

**Comment by nowaalex** [comment]
Hi @aaron5670
I have fixed that, upgrade to 2.6.3
